### ISSUE TITLE
Sample TURL Documentation

### ISSUE THREAD

**Issue by nickzana** [j0rsa/transmission-rpc#13]
It took me (although admittedly I'm not very experienced in Rust) a fair bit of digging through the code to realize that I needed to add `/transmission/rpc/` to the end of my URL.  As far as I can tell, all of the examples rely on the TURL environment variable in a .env file, for which there is no example. My understanding is that this is the default and not specific to my configuration, so it might be helpful to include in the README or an example .env file.

**Comment by red-avtovo** [comment]
related to #2

**Comment by red-avtovo** [comment]
Hi @nickzana! Indeed you need to provide the full path to `rpc` endpoint. Will add it to the docs
