### ISSUE TITLE
examples/torrent-get.rs panics 

### ISSUE THREAD

**Issue by mabushey** [j0rsa/transmission-rpc#2]
I'm extremely new to rust...

$ rustc --version
rustc 1.41.0

```
$ cargo new trans
$ cd trans
$ echo 'transmission-rpc = "0.2.2"' >> Cargo.toml
$ echo 'dotenv = "0.15.0"' >> Cargo.toml
$ echo 'tokio = "0.2.21"' >> Cargo.toml
$ echo 'log = "0.4.0"' >> Cargo.toml
$ echo 'env_logger = "0.7.1"' >> Cargo.toml
$ wget https://raw.githubusercontent.com/j0rsa/transmission-rpc/master/examples/torrent-get.rs -O src/main.rs
$ vim .env ## Add TURL, TUSER, TPWD
$ RUST_LOG=info
$ cargo build
   Compiling trans v0.1.0 (/home/michael/rust/trans)
    Finished dev [unoptimized + debuginfo] target(s) in 4.91s
```
$ ./target/debug/trans
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Any ideas? session-get.rs has the same error.

**Comment by mabushey** [comment]
In session-get.rs, this is the line that panics:
`let response: Result<RpcResponse<SessionGet>> = client.session_get().await;`

**Comment by red-avtovo** [comment]
Hey, @mabushey!
Thank you for your interest to this project.

I followed your steps and I think I found the root cause of your issue. What is your `TURL` look like? This URL should lead to transmission RPC api, so it should be in a format `http(s)://host:port/transmission/rpc`

**Comment by red-avtovo** [comment]
Basically it fails after the first call, which tries to authenticate you and it expects some headers from the server. Since you provided a wrong URL, your call was redirected, but it returned no required headers and thus it panicked.

**Comment by mabushey** [comment]
Thanks @red-avtovo !

You are correct. I updated the TURL, and the get-session example works.

I appreciate the help. :)
