### ISSUE TITLE
It seems that the library crash instead of return error when we use the wrong auth info.

### ISSUE THREAD

**Issue by ngoquang2708** [j0rsa/transmission-rpc#25]
With the wrong auth info is provided. When we exec any function that has response fields, if those fields are not optional then there is no data for the json decoder to work with, cause crash.

**Comment by red-avtovo** [comment]
Related to https://github.com/j0rsa/transmission-rpc/issues/15
It is indeed a valid bug. Can you propose a fix for that?

**Comment by ngoquang2708** [comment]
I think we should check the HTTP response code [here](https://github.com/j0rsa/transmission-rpc/blob/018d94f51ee59d40417b391b31b64366f7218184/src/lib.rs#L430) before attempt to decode the response body.

**Comment by ngoquang2708** [comment]
May be ```resp.error_for_status();``` could help.

**Comment by ngoquang2708** [comment]
Could look like this
```
        let resp: reqwest::Response = rq.send().await?;
        match resp.error_for_status() {
            Ok(rsp) => {
                let rpc_response: RpcResponse<RS> = resp.json().await?;
                info!("Response body: {:#?}", rpc_response);
                Ok(rpc_response)
            }
            Err(err) => Err(err)
        }
```
but I got compile error at ```Err(err) => Err(err)```. I am new to Rust :D
