### ISSUE TITLE
Implement integrational tests

### ISSUE THREAD

**Issue by red-avtovo** [j0rsa/transmission-rpc#32]
Start a local transmission instance in docker container and run all tests against it to verify the functionality

**Comment by red-avtovo** [comment]
@ngoquang2708 would you be interested into developing such thing?

**Comment by ngoquang2708** [comment]
I am new to Rust all the things you have wrote. Can you give me some insight so I could try.

**Comment by red-avtovo** [comment]
You would need to write a `docker-compose.yaml` file and update the CI in terms, that the command will be executed:
```
docker-compose up -d
```
Then you should run cargo test
And check that all tests passed
Then you can optionally shutdown the container (it might be shutted down automatically on cleanup)

**Comment by ngoquang2708** [comment]
Per #34, Where should we place .env and docker-compose.yaml file for tests?
