### ISSUE TITLE
add support for more info fields

### ISSUE THREAD

**Issue by notjedi** [j0rsa/transmission-rpc#47]
the transmission [rpc spec file](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md) lists a few more keys in the response of `torrent-get` method. here are a few fields that are listed but are not supported by this crate:

1. `peer-limit`
2. `pieces`
3. `pieceCount`
4. `pieceSize`
5. `rateDownload`

are these intentionally not included because for some backward compatibility of the rpc version or something like that? if not i would be happy to open a PR.

this seems to be the case for more or less all the method calls. they only seem to take into account a limited number of fields.

**Comment by notjedi** [comment]
just took a look at a [PR](https://github.com/hekmon/transmissionrpc/pull/14) from a different repo, seems like the above mentioned fields have been supported well before the latest RPC version.

**Comment by red-avtovo** [comment]
I was not very much interested in those pieces and thus they were out. Feel free to extend the lib

**Comment by red-avtovo** [comment]
I will close this issue for now. If you want to contribute yourself or catch anyone's attention to it, feel free to refer to this ticket
